# Generated by Django 6.0.3 on 2026-03-26 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_fee_holiday'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fee',
        ),
    ]
